
-1
down vote
favorite
I have Anaconda 5.0, Windows 10.
I have installed Tensorflow with pip install tensorflow in the Anaconda Prompt.
Installation was successful. The test suggested on the website worked as expected.
But now I cannot install any other package with pip install. For instance when I run:

pip install memory-profiler I get:

Exception:
Traceback (most recent call last):
  File "C:\Python\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Python\Anaconda3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Python\Anaconda3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Python\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Python\Anaconda3\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "C:\Python\Anaconda3\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Python\Anaconda3\lib\site-packages\pip\index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "C:\Python\Anaconda3\lib\site-packages\pip\index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "C:\Python\Anaconda3\lib\site-packages\pip\index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "C:\Python\Anaconda3\lib\site-packages\pip\index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\Python\Anaconda3\lib\site-packages\pip\index.py", line 811, in get_page
    inst = cls(resp.content, resp.url, resp.headers)
  File "C:\Python\Anaconda3\lib\site-packages\pip\index.py", line 731, in __init__
    namespaceHTMLElements=False,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'
How can I remedy this?

The problem persists after running:

conda upgrade pip

Also, the solution provided by Romeo, here, does not work for me.

python tensorflow anaconda
shareimprove this question
edited Oct 18 at 17:42
asked Oct 18 at 11:09

Sandu Ursu
348
  	 	
Possible duplicate of pip throws TypeError: parse() got an unexpected keyword argument 'transport_encoding' when trying to install new packages â€“ Goyo Oct 18 at 11:44
add a comment
1 Answer
active oldest votes
up vote
1
down 

Solved by running:
conda install --force html5lib

(credit: Mike Lanzetta)
